language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "292e28a2b3eb6b4eaf8c56ef68302478cd1aff1b"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master