language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "773d41b2d7bb3828390d2db9e122f57d124a4271"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master