language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "b5f39cb60bf672ac46192f1dbcabbf6b289cba38"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master