language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "af1bf0d933a1943d710962e6d5ab28646bc4ccdb"  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master